[Twitch]
apkmirror-dlurl = "https://apkmirror.com/apk/twitch-interactive-inc/twitch/"
arch = "arm64-v8a"
version = "16.9.1"

[Twitter]
apkmirror-dlurl = "https://apkmirror.com/apk/twitter-inc/twitter/"
version = "10.34.0"
included-patches = "'Dynamic color' 'Hide ads' 'Unlock downloads'"
exclusive-patches = true

